### PR TITLE
Use systemd unit files for systemd systems.

### LINKED ISSUE #20: Ansible 2.2 service module requires systemd unit file for Ubuntu 16.04
Ansible 2.2 introduced some changes to the way the `service` module works with older init scripts, so the following happens under Ubuntu 16.04 if using Ansible 2.2+:

```
TASK [arknoll.selenium : Ensure selenium is running] ***************************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'selenium'\": "}
```

For my roles that were encountering similar issues, I had to add a systemd unit file and this solved the issue because the `service` module can use that instead of the custom init script.

See:

  - https://github.com/geerlingguy/ansible-role-mailhog/commit/44b88ccc52eb732acdbaabf21101030d637106c0
  - https://github.com/geerlingguy/ansible-role-firewall/commit/6187db624d3d151c1a598709c9a50ce49ed87d80

### PR DESCRIPTION
**Pull request by kporras07**
This should fix #20

### CODE REVIEW

**Comment by kporras07** [comment]
@geerlingguy, @arknoll 
It's failing idempotence tests for all of the systemd systems. It's failing in the ensure service is running step.
It's also failing centos6 and ubuntu 12.04 for an unresolved dependency while installing chrome

Any ideas?

**Comment by kporras07** [comment]
So, I fixed the idempotence problem. Only missing the unresolved dependency.

**Comment by geerlingguy** [comment]
Fixed the broken test by installing FireFox (instead of Chrome) on older OSes where Chrome isn't supported: https://github.com/arknoll/ansible-role-selenium/pull/24

**Comment by kporras07** [comment]
awesome! Thanks @geerlingguy

**Pull request merged**
