### PR TITLE
Fix broken tests by installing unzip dependency.

### PR DESCRIPTION
**Pull request by geerlingguy**

### CODE REVIEW

**Comment by geerlingguy** [comment]
Tests that are passing:
- [x] CentOS 7
- [ ] CentOS 6
- [x] Ubuntu 16.04
- [ ] Ubuntu 14.04
- [ ] Ubuntu 12.04

**Comment by arknoll** [comment]
Thanks @geerlingguy!

**Comment by geerlingguy** [comment]
For 14.04, it seems the init script is causing a problem with idempotence.

For 12.04, it looks like [Chrome isn't installable on 12.04](http://askubuntu.com/a/774035/88829), so we can either drop 12.04 or dynamically change the default to Firefox instead, just for 12.04.

**Comment by geerlingguy** [comment]
@arknoll - it looks like Google doesn't support either Ubuntu 12.04 or CentOS 6: http://superuser.com/a/878733/80658

We should either drop official support for those OSes or switch the default on the fly to Firefox.

**Pull request merged**
